FCYTSPRUN-20-reglamentoinvestigacion Se creo la pagina de reglamento …
FCYT-TI/fcytuncaweb pull request #13
Opened 2024-08-23 01:14 UTC by JulioJavalosc

Pagina de reglamento de investigacion de la fcyt

2024-08-23 16:18 UTC, mathwfct commented
Resolver los conflictos de la rama

2024-08-23 16:20 UTC, mathwfct requested changes
Aplicar los cambios requeridos

2024-08-23 16:20 UTC, mathwfct commented on templates/reglamento_investigacion.html
> +                <li>Reglamento General de Investigación de la Universidad Nacional de Caaguazú. Aprobado por Resolución del C.S.U. N° 107/2015, según Acta N° 29/2015, de fecha 17 de noviembre de 2.01
usar 2015 en vez de 2.015

2024-11-12 01:49 UTC, FerSanM commented
cambios realizados correctamente

2024-11-12 01:53 UTC, FerSanM approved these changes
cambios correctos

2024-11-12 01:54 UTC, merged