FCYTSPRUN-10-ConsejoDirectivo Se añadio la pagina de consejo directiv…
FCYT-TI/fcytuncaweb pull request #5
Opened 2024-08-20 16:38 UTC by JulioJavalosc

Pagina del Consejo Directivo de la Fcyt

2024-08-21 17:06 UTC, cmmedina918 requested changes
Favor mirar los comentarios y modificar

2024-08-21 17:06 UTC, cmmedina918 commented on templates/consejo.html
> +            <td><img src="{% static "img/usuario.jpg" %}"><p>Prof. Ing. Roberto Rosa Chávez Ayala</p><p><b>ViceDecano</b></p><p>correo@fctunca.edu.py</p></td>
Deberia ser Vicedecano

2024-08-21 17:06 UTC, cmmedina918 commented on templates/consejo.html
> +            <td><img src="{% static "img/usuario.jpg" %}"><p>Prof. Ing. Alfredo Moreno Sosa</p><p><b>Decano</b></p><p>correo@fctunca.edu.py</p></td>
Cambiar los nombres a H3, el cargo a H4 y agrandar la imagen

2024-08-21 17:25 UTC, cmmedina918 reviewed
Aplicar los cambios sugeridos

2024-08-21 17:25 UTC, cmmedina918 commented on templates/consejo.html
> +          <p id="Titutlo-Consejo"><u>Miembros del Consejo Directivo de la Facultad de Ciencias y Tecnologías</u></p>
Utilizar la etiqueta h2 en vez de párrafo y es redundante que se especifique que son de la facultad, ya se entiende con Miembros del Consejo Directivo.

2024-08-21 17:25 UTC, cmmedina918 commented on templates/consejo.html
> +            <td><img src="{% static "img/usuario.jpg" %}"><p>Prof. Ing. Alfredo Moreno Sosa</p><p><b>Decano</b></p><p>correo@fctunca.edu.py</p></td>
Utilizar el template base, específicamente la sección de team members, si necesita ayuda contactar con el scrum master.
![Captura de pantalla 2024-08-21 132229](https://github.com/user-attachments/assets/cbeb95db-0bd3-4d0c-b2b4-dcd592f8483a)

2024-08-22 21:24 UTC, mathwfct commented
Actualizar la rama con develop, solicitar asistencia de ser necesario

2024-08-22 21:49 UTC, mathwfct requested changes
Aplicar cambios

2024-08-22 21:49 UTC, mathwfct commented on templates/consejo.html
> +          <h2 id="Titutlo-Consejo"><u>Miembros del Consejo Directivo</u></h2>
Eliminar el subrayado

2024-08-22 21:49 UTC, mathwfct commented on templates/consejo.html
> +                  <a href=""><i class="bi bi-twitter"></i></a>
utilizar el icon bi-twitter-x

2024-08-22 21:49 UTC, mathwfct commented on templates/consejo.html
> +                <span>Decano</span>
utilizar un color mas oscuro o negro

2024-08-22 21:49 UTC, mathwfct commented on templates/consejo.html
> +                <p>correo@fctunca.edu.py</p>
Evitar utilizar la tipografia en cursivas

2024-08-22 22:38 UTC, mathwfct approved these changes

2024-08-22 22:39 UTC, merged