FCYTSPRUN-11-PaginaResoluciones Se desarrolló la página HTML que mues…
FCYT-TI/fcytuncaweb pull request #6
Opened 2024-08-21 00:15 UTC by Carlos-Coronel

Pagina de resoluciones de la fcyt

2024-08-21 15:36 UTC, JulioJavalosc commented
la rama fcytsprun-11 necesita actualizarse con la rama develop para resolver el conflicto existente, esto se realiza haciendo un merge desde la rama develop, se adjunta imagen de ejemplo : 
![Screenshot_25](https://github.com/user-attachments/assets/e0d8f648-c43b-4031-a912-3dca57c1ce19)

2024-08-21 16:37 UTC, JulioJavalosc reviewed
Aplicar los cambios solicitados

2024-08-21 16:37 UTC, JulioJavalosc commented on templates/resolucion.html
> +{% include "header.html" %}
todo el proyecto debe estar dentro del main original del template base , también debe contener la sección del breadcrum , luego de esta sección continuar con la estructura actual

2024-08-21 16:37 UTC, JulioJavalosc commented on templates/resolucion.html
> +            <h1>Resoluciones</h1>
eliminar este titulo ya que el template base posee su propio titulo

2024-08-21 16:37 UTC, JulioJavalosc commented on templates/resolucion.html
> +                <input type="search" placeholder="Search Data...">
utilizar información en español para toda interacción dentro del proyecto ,  agregar un icono de búsqueda antes de la descripción , el cuadro de búsqueda debe estar visual en todo momento para el usuario , adjunto imagen de ejemplo : 
![Screenshot_26](https://github.com/user-attachments/assets/1a13d743-adc4-4fdf-ac34-c30cdc9d9338)
mantener la posición actual del buscador

2024-08-22 20:33 UTC, JulioJavalosc reviewed
Aplicar los cambios solicitados

2024-08-22 20:33 UTC, JulioJavalosc commented on templates/resolucion.html
> +    <section class="breadcrumbs" style="padding-top: 0px; margin-top: 0px">
Utilizar para el titulo el formato del template_base.html adjunto imagen de ejemplo de otra pagina de como deberia visualizarse
![Screenshot_28](https://github.com/user-attachments/assets/6abc4d7a-70f5-4239-a5a5-21066e1accb8)

2024-08-22 20:33 UTC, JulioJavalosc commented on templates/resolucion.html
> +            <input type="search" placeholder="Buscar datos ...">
indicar al usuario el borde del buscador en todo momento adjunto imagen de ejemplo
![Screenshot_29](https://github.com/user-attachments/assets/b7b73024-199d-44d8-88b4-f1940da26893)

2024-08-22 22:16 UTC, mathwfct requested changes
Aplicar los cambios requeridos

2024-08-22 22:16 UTC, mathwfct commented on templates/resolucion.html
> +    <section class="table__body">
alinear la tabla en direccion al nav
![image](https://github.com/user-attachments/assets/d102d32c-60d2-408a-b8b3-cc4bd722ab47)
adjunto imagen referencial en base al diseño actual

2024-08-22 22:16 UTC, mathwfct commented on templates/resolucion.html
> +            <input type="search" placeholder="Buscar ...">
ajustar la posicion del icono de busqueda y agregar color

2024-08-22 23:07 UTC, mathwfct approved these changes

2024-08-22 23:07 UTC, merged